"""refactor company hr relationship

Revision ID: 1e96e795a937
Revises: 0afdf6b3dbce
Create Date: 2026-05-07 00:35:39.772486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e96e795a937'
down_revision: Union[str, Sequence[str], None] = '0afdf6b3dbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_company_assignments',
    sa.Column('hr_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hr_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hr_id', 'company_id')
    )
    op.drop_constraint(op.f('companies_created_by_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('companies_created_by_fkey'), 'companies', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_table('hr_company_assignments')
    # ### end Alembic commands ###
