"""Add Harvard standard JSONB fields to candidates

Revision ID: 26578b1900af
Revises: ff4af8364bc2
Create Date: 2026-04-20 15:31:45.210798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26578b1900af'
down_revision: Union[str, Sequence[str], None] = 'ff4af8364bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'certifications')
    op.drop_column('candidates', 'projects')
    op.drop_column('candidates', 'work_experience')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'about_me')
    op.drop_column('candidates', 'avatar_url')
    # ### end Alembic commands ###
