"""Add industry and logo_url to companies table

Revision ID: 2ad1ac42cd42
Revises: c3c136253b5c
Create Date: 2026-05-11 11:57:34.194483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad1ac42cd42'
down_revision: Union[str, Sequence[str], None] = 'c3c136253b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
