"""Add tech_skills and soft_skills to candidates

Revision ID: 33cad9101599
Revises: 1d581b0a70b8
Create Date: 2026-05-08 20:03:11.363018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33cad9101599'
down_revision: Union[str, Sequence[str], None] = '1d581b0a70b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('tech_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidates', sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'soft_skills')
    op.drop_column('candidates', 'tech_skills')
    # ### end Alembic commands ###
