"""update match_score precision to 5,2

Revision ID: 55a9352fefce
Revises: b9ace8f4dff5
Create Date: 2026-05-12 00:26:20.916057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a9352fefce'
down_revision: Union[str, Sequence[str], None] = 'b9ace8f4dff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'match_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'match_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
