"""Add github_url and linkedin_url to candidates

Revision ID: 7f87dbbeb088
Revises: 33cad9101599
Create Date: 2026-05-09 01:58:30.814294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f87dbbeb088'
down_revision: Union[str, Sequence[str], None] = '33cad9101599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'linkedin_url')
    op.drop_column('candidates', 'github_url')
    # ### end Alembic commands ###
