"""add_more_job_fields

Revision ID: c3c136253b5c
Revises: 7f87dbbeb088
Create Date: 2026-05-10 00:47:21.972511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c136253b5c'
down_revision: Union[str, Sequence[str], None] = '7f87dbbeb088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('salary_range', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('job_descriptions', sa.Column('requirements_text', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('benefits_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'benefits_text')
    op.drop_column('job_descriptions', 'requirements_text')
    op.drop_column('job_descriptions', 'deadline')
    op.drop_column('job_descriptions', 'salary_range')
    op.drop_column('job_descriptions', 'location')
    # ### end Alembic commands ###
